class LocalizationService {
  static const Map<String, Map<String, String>> _translations = {
    'Português': {
      // --- Chaves de UI E TELAS ---
      'selecao_idioma_titulo': 'SELECIONE UM IDIOMA',
      'erro_selecao_idioma': 'Por favor, selecione um idioma antes de continuar.',
      'botao_confirmar_selecao': 'Confirmar Seleção',
      'tela_inicial': 'Menu Principal',
      'botao_iniciar': 'Começar Simulação',
      'descricao_app': 'Ferramenta para cálculo de propriedades de gás natural.',
      'titulo': 'ENTRADA DE PROPRIEDADES DO GÁS',
      'aba_densidade': 'DENSIDADE',
      'aba_massa': 'MASSA MOLECULAR',
      'aba_propriedades': 'COMPOSIÇÃO',
      'densidade_seco': 'Gás Seco',
      'densidade_umido': 'Gás Úmido',
      'label_densidade': 'Valor da Densidade ({0}) (Ex: 0.8)',
      'label_massa_molecular': 'Massa Molecular (sem unidade)',
      'dropdown_selecione': 'Selecione o Componente',
      'label_fracao': 'Fração Molar (Ex: 0.15)',
      'botao_adicionar': 'Adicionar',
      'botao_confirmar': 'CONFIRMAR',
      'cabecalho_componente': 'Componente',
      'cabecalho_fracao': 'Fração',
      'cabecalho_massa_molecular': 'Ma',
      'cabecalho_pc': 'Psc',
      'cabecalho_tc': 'Tsc',
      'total_somatoria': 'Somatória Total:',
      'erro_tabela_vazia': 'Nenhum componente informado.',
      'erro_zero': 'O valor deve ser maior que 0.',
      'erro_tabela_zero': 'A somatória das frações deve ser maior que 0.',
      'sucesso_confirmar': 'Dados confirmados com sucesso!',
      'erro_fracao_invalida': 'Por favor, insira uma fração decimal válida (> 0).',
      'erro_max_fracao_atingido': 'A soma total não pode exceder 1.0. Capacidade restante: {0}.',
      'erro_soma_maior_um': 'Erro: A soma total excedeu 1.0.',
      'componente_adicionado': 'Componente adicionado/atualizado com sucesso.',
      'componente_removido': 'Componente removido.',
      'com_contaminantes': 'Com Componentes',
      'sem_contaminantes': 'Sem Componentes',
      'label_contaminantes': 'Contaminantes',
      'erro_massa_invalida': 'Por favor, insira valor de Massa Molecular".',
      'erro_sem_componentes': 'Adicione pelo menos um componente ou selecione "Sem Componentes".',
      'erro_densidade_invalida': 'Por favor, insira um valor de Densidade válido.',
      'erro_soma_menor_igual_zero': 'A somatória das frações deve ser estritamente maior que zero (0).',
      "erro_inserir_valores_validos": "Por favor, insira valores válidos de Pressão e Temperatura.",
      'titulo_reservatorio': 'DADOS DO RESERVATÓRIO',
      
      // Propriedades Calculadas (Display)
      'tela_reservatorio_titulo': 'DADOS DO RESERVATÓRIO',
      'propriedades_calculadas': 'PROPRIEDADES CALCULADAS DO GÁS',

      // Entradas do Reservatório (Input)
      'titulo_dados_reservatorio': 'CONDIÇÕES DO RESERVATÓRIO',
      'label_pressao_reservatorio': 'Pressão do Reservatório', 
      'label_temperatura_reservatorio': 'Temperatura do Reservatório',

      // Propriedades e Unidades
      'prop_ppc': 'Pressão Pseudo Crítica (Ppc)',
      'prop_ppr': 'Pressão Pseudo Reduzida (Ppr)',
      'prop_tpc': 'Temperatura Pseudo Crítica (Tpc)',
      'prop_tpr': 'Temperatura Pseudo Reduzida (Tpr)',
      'prop_massa_molecular': 'Massa Molecular (M)',
      'prop_massa_especifica': 'Massa Específica (γg)',
      'prop_densidade': 'Densidade Relativa (ρg)',
      'prop_viscosidade': 'Viscosidade (μg)',
      'prop_compressibilidade': 'Compressibilidade (cg)',
      'prop_compressibilidade_reduzida': 'Compressibilidade Reduzida (cr)',
      'prop_fator_compressibilidade': 'Fator de Compressibilidade (z)',
      'prop_fator_volume_formacao': 'Fator Volume-Formação do Gás (Bg)',

      // Unidades de Pressão e Temperatura (Para SuffixText ou Seleção)
      'unidade_pressao_psia': 'psia',
      'unidade_pressao_kpa': 'kPa',
      'unidade_pressao_bar': 'bar',
      'unidade_pressao_kgf_cm2': 'kgf/cm²',
      'unidade_pressao_atm': 'atm',      
      'unidade_temperatura_f': 'ºF',
      'unidade_temperatura_c': 'ºC',
      'unidade_temperatura_k': 'K',
      'unidade_temperatura_r': '°R',
      'unidade_massa_molecular': 'g/mol',
      'unidade_massa_especifica': 'kg/m³',
      'unidade_viscosidade': 'cP',
      'unidade_compressibilidade': '1/psi',
      'unidade_fator_volume_formacao': 'ft³/scf',
      'unidade_adimensional': '',
      
      // Botões e Erros
      'botao_calcular': 'CALCULAR',
      'erro_pressao_temperatura': 'Pressão e Temperatura devem ser valores positivos válidos.',

      // --- Componentes de Gás ---
      'Methane': 'Metano (CH₄)',
      'Ethane': 'Etano (C₂H₆)',
      'Propane': 'Propano (C₃H₈)',
      'nButane': 'n-Butano (n-C₄H₁₀)',
      'iButane': 'i-Butano (i-C₄H₁₀)',
      'nPentane': 'n-Pentano (n-C₅H₁₂)',
      'iPentane': 'i-Pentano (i-C₅H₁₂)',
      'nHexane': 'n-Hexano (n-C₆H₁₄)',
      'nHeptane': 'n-Heptano (n-C₇H₁₆)',
      'nOctane': 'n-Octano (n-C₈H₁₈)',
      'nNonane': 'n-Nonano (n-C₉H₂₀)',
      'nDecane': 'n-Decano (n-C₁₀H₂₂)',
      'Hydrogen': 'Hidrogênio (H₂)',
      'Nitrogen': 'Nitrogênio (N₂)',
      'Oxygen': 'Oxigênio (O₂)',
      'HydrogenSulfide': 'Sulfeto de Hidrogênio (H₂S)',
      'CarbonDioxide': 'Dióxido de Carbono (CO₂)',
      'WaterVapor': 'Vapor d\'água (H₂O)',
      'Helium': 'Hélio',
      'Argon': 'Argônio',
    },
    'Inglês': {
      // --- Chaves de UI E TELAS ---
      'selecao_idioma_titulo': 'SELECT A LANGUAGE',
      'erro_selecao_idioma': 'Please select a language before continuing.',
      'botao_confirmar_selecao': 'Confirm Selection',
      'tela_inicial': 'Main Menu',
      'botao_iniciar': 'Start Simulation',
      'descricao_app': 'Tool for natural gas property calculation.',
      'titulo': 'GAS PROPERTIES INPUT',
      'aba_densidade': 'DENSITY',
      'aba_massa': 'MOLECULAR WEIGHT',
      'aba_propriedades': 'COMPOSITION',
      'densidade_seco': 'Dry Gas',
      'densidade_umido': 'Wet Gas',
      'label_densidade': 'Density Value ({0}) (Ex: 0.8)',
      'label_massa_molecular': 'Molecular Weight (no unit)',
      'dropdown_selecione': 'Select Component',
      'label_fracao': 'Mole Fraction (Ex: 0.15)',
      'botao_adicionar': 'Add',
      'botao_confirmar': 'CONFIRM',
      'cabecalho_componente': 'Component',
      'cabecalho_fracao': 'Fraction',
      'cabecalho_massa_molecular': 'Ma',
      'cabecalho_pc': 'Psc',
      'cabecalho_tc': 'Tsc',
      'total_somatoria': 'Total Sum:',
      'erro_zero': 'The value must be greater than 0.',
      'erro_tabela_vazia': 'No component provided.',
      'erro_tabela_zero': 'The sum of fractions must be greater than 0.',
      'sucesso_confirmar': 'Data successfully confirmed!',
      'erro_fracao_invalida': 'Please enter a valid decimal fraction (> 0).',
      'erro_max_fracao_atingido': 'Total sum cannot exceed 1.0. Remaining capacity: {0}.',
      'erro_soma_maior_um': 'erro: Total sum exceeded 1.0.',
      'componente_adicionado': 'Component successfully added/updated.',
      'componente_removido': 'Component removed.',
      'com_contaminantes': 'With Components',
      'sem_contaminantes': 'Without Components',
      'label_contaminantes': 'Contaminants',
      'erro_massa_invalida': 'Please enter a valid Molecular Weight".',
      'erro_sem_componentes': 'Add at least one component or select "Without Components".',
      'erro_densidade_invalida': 'Please enter a valid Density value.',
      'erro_soma_menor_igual_zero': 'The total sum of fractions must be strictly greater than zero (0).',
      "erro_inserir_valores_validos": "Please enter valid Pressure and Temperature values.",
      'titulo_reservatorio': 'RESERVOIR DATA',
      
      // Calculated Properties (Display)
      'tela_reservatorio_titulo': 'RESERVOIR DATA',
      'propriedades_calculadas': 'CALCULATED GAS PROPERTIES',

      // Reservoir Inputs (Input)
      'titulo_dados_reservatorio': 'RESERVOIR CONDITIONS',
      'label_pressao_reservatorio': 'Reservoir Pressure',
      'label_temperatura_reservatorio': 'Reservoir Temperature',

      // Propriedades e Unidades
      'prop_ppc': 'Pseudocritical Pressure (Ppc)',
      'prop_ppr': 'Pseudoreduced Pressure (Ppr)',
      'prop_tpc': 'Pseudocritical Temperature (Tpc)',
      'prop_tpr': 'Pseudoreduced Temperature (Tpr)',
      'prop_massa_molecular': 'Molecular Weight (M)',
      'prop_massa_especifica': 'Specific Mass (γg)',
      'prop_densidade': 'Relative Density (ρg)',
      'prop_viscosidade': 'Viscosity (μg)',
      'prop_compressibilidade': 'Compressibility (cg)',
      'prop_compressibilidade_reduzida': 'Reduced Compressibility (cr)',
      'prop_fator_compressibilidade': 'Compressibility Factor (z)',
      'prop_fator_volume_formacao': 'Gas Formation Volume Factor (Bg)',

      // Unidades de Pressão e Temperatura (Para SuffixText ou Seleção)
      'unidade_pressao_psia': 'psia',
      'unidade_pressao_kpa': 'kPa',
      'unidade_pressao_bar': 'bar',
      'unidade_pressao_kgf_cm2': 'kgf/cm²',
      'unidade_pressao_atm': 'atm',      
      'unidade_temperatura_f': 'ºF',
      'unidade_temperatura_c': 'ºC',
      'unidade_temperatura_k': 'K',
      'unidade_temperatura_r': '°R',
      'unidade_massa_molecular': 'g/mol',
      'unidade_massa_especifica': 'kg/m³',
      'unidade_viscosidade': 'cP',
      'unidade_compressibilidade': '1/psi',
      'unidade_fator_volume_formacao': 'ft³/scf',
      'unidade_adimensional': '',
      
      // Buttons and Errors
      'botao_calcular': 'CALCULATE',
      'erro_pressao_temperatura': 'Pressure and Temperature must be valid positive values.',

      // --- Componentes de Gás ---
      'Methane': 'Methane (CH₄)',
      'Ethane': 'Ethane (C₂H₆)',
      'Propane': 'Propane (C₃H₈)',
      'nButane': 'n-Butane (n-C₄H₁₀)',
      'iButane': 'i-Butane (i-C₄H₁₀)',
      'nPentane': 'n-Pentane (n-C₅H₁₂)',
      'iPentane': 'i-Pentane (i-C₅H₁₂)',
      'nHexane': 'n-Hexane (n-C₆H₁₄)',
      'nHeptane': 'n-Heptane (n-C₇H₁₆)',
      'nOctane': 'n-Octane (n-C₈H₁₈)',
      'nNonane': 'n-Nonane (n-C₉H₂₀)',
      'nDecane': 'n-Decane (n-C₁₀H₂₂)',
      'Hydrogen': 'Hydrogen (H₂)',
      'Nitrogen': 'Nitrogen (N₂)',
      'Oxygen': 'Oxygen (O₂)',
      'HydrogenSulfide': 'Hydrogen Sulfide (H₂S)',
      'CarbonDioxide': 'Carbon Dioxide (CO₂)',
      'WaterVapor': 'Water Vapor (H₂O)',
      'Helium': 'Helium',
      'Argon': 'Argon',
    },
    'Espanhol': {
      // --- Chaves de UI E TELAS ---
      'selecao_idioma_titulo': 'SELECCIONA UN IDIOMA',
      'erro_selecao_idioma': 'Por favor, selecciona un idioma antes de continuar.',
      'botao_confirmar_selecao': 'Confirmar Selección',
      'tela_inicial': 'Menú Principal',
      'botao_iniciar': 'Iniciar Simulación',
      'descricao_app': 'Herramienta para el cálculo de propiedades de gas natural.',
      'titulo': 'ENTRADA DE PROPIEDADES DEL GAS',
      'aba_densidade': 'DENSIDAD',
      'aba_massa': 'MASA MOLECULAR',
      'aba_propriedades': 'COMPOSICIÓN',
      'densidade_seco': 'Gas Seco',
      'densidade_umido': 'Gas Húmedo',
      'label_densidade': 'Valor de Densidad ({0}) (Ej: 0.8)',
      'label_massa_molecular': 'Masa Molecular (sin unidad)',
      'dropdown_selecione': 'Selecciona el Componente',
      'label_fracao': 'Fracción Molar (Ej: 0.15)',
      'botao_adicionar': 'Añadir',
      'botao_confirmar': 'CONFIRMAR',
      'cabecalho_componente': 'Componente',
      'cabecalho_fracao': 'Fracción',
      'cabecalho_massa_molecular': 'Ma',
      'cabecalho_pc': 'Psc',
      'cabecalho_tc': 'Tsc',
      'total_somatoria': 'Suma Total:',
      'erro_zero': 'El valor debe ser mayor que 0.',
      'erro_tabela_vazia': 'Ningún componente informado.',
      'erro_tabela_zero': 'La suma de fracciones debe ser mayor que 0.',
      'sucesso_confirmar': 'Datos confirmados con éxito!',
      'erro_fracao_invalida': 'Por favor, introduce una fracción decimal válida (> 0).',
      'erro_max_fracao_atingido': 'La suma total no puede exceder 1.0. Capacidad restante: {0}.',
      'erro_soma_maior_um': 'erro: La suma total superó 1.0.',
      'componente_adicionado': 'Componente añadido/actualizado con éxito.',
      'componente_removido': 'Componente eliminado.',
      'com_contaminantes': 'Con Componentes',
      'sem_contaminantes': 'Sin Componentes',
      'label_contaminantes': 'Contaminantes',
      'erro_massa_invalida': 'Por favor, introduzca un valor de Masa Molecular válido".',
      'erro_sem_componentes': 'Agregue al menos un componente o seleccione "Sin Componentes".',
      'erro_densidade_invalida': 'Por favor, introduzca un valor de Densidad válido.',
      'erro_soma_menor_igual_zero': 'La suma total de fracciones debe ser estrictamente mayor que cero (0).',
      "erro_inserir_valores_validos": "Por favor, ingrese valores válidos de Presión y Temperatura.",
      'titulo_reservatorio': 'DATOS DEL YACIMIENTO',
      
      // Propriedades Calculadas (Display)
      'tela_reservatorio_titulo': 'DATOS DEL YACIMIENTO',
      'propriedades_calculadas': 'PROPIEDADES CALCULADAS DEL GAS',

      // Entradas del Yacimiento (Input)
      'titulo_dados_reservatorio': 'CONDICIONES DEL YACIMIENTO',
      'label_pressao_reservatorio': 'Presión del Yacimiento',
      'label_temperatura_reservatorio': 'Temperatura del Yacimiento',

      // Propriedades e Unidades
      'prop_ppc': 'Presión Pseudocrítica (Ppc)',
      'prop_ppr': 'Presión Pseudoreducida (Ppr)',
      'prop_tpc': 'Temperatura Pseudocrítica (Tpc)',
      'prop_tpr': 'Temperatura Pseudoreducida (Tpr)',
      'prop_massa_molecular': 'Masa Molecular (M)',
      'prop_massa_especifica': 'Masa Específica (γg)',
      'prop_densidade': 'Densidad Relativa (ρg)',
      'prop_viscosidade': 'Viscosidad (μg)',
      'prop_compressibilidade': 'Compresibilidad (cg)',
      'prop_compressibilidade_reduzida': 'Compresibilidad Reducida (cr)',
      'prop_fator_compressibilidade': 'Factor de Compresibilidad (z)',
      'prop_fator_volume_formacao': 'Factor Volumen-Formación del Gas (Bg)',

      // Unidades de Pressão e Temperatura (Para SuffixText ou Seleção)
      'unidade_pressao_psia': 'psia',
      'unidade_pressao_kpa': 'kPa',
      'unidade_pressao_bar': 'bar',
      'unidade_pressao_kgf_cm2': 'kgf/cm²',
      'unidade_pressao_atm': 'atm',      
      'unidade_temperatura_f': 'ºF',
      'unidade_temperatura_c': 'ºC',
      'unidade_temperatura_k': 'K',
      'unidade_temperatura_r': '°R',
      'unidade_massa_molecular': 'g/mol',
      'unidade_massa_especifica': 'kg/m³',
      'unidade_viscosidade': 'cP',
      'unidade_compressibilidade': '1/psi',
      'unidade_fator_volume_formacao': 'ft³/scf',
      'unidade_adimensional': '', 
      
      // Botões e Errores
      'botao_calcular': 'CALCULAR',
      'erro_pressao_temperatura': 'Presión y Temperatura deben ser valores positivos válidos.',

      // --- Componentes de Gás ---
      'Methane': 'Metano (CH₄)',
      'Ethane': 'Etano (C₂H₆)',
      'Propane': 'Propano (C₃H₈)',
      'nButane': 'n-Butano (n-C₄H₁₀)',
      'iButane': 'i-Butano (i-C₄H₁₀)',
      'nPentane': 'n-Pentano (n-C₅H₁₂)',
      'iPentane': 'i-Pentano (i-C₅H₁₂)',
      'nHexane': 'n-Hexano (n-C₆H₁₄)',
      'nHeptane': 'n-Heptano (n-C₇H₁₆)',
      'nOctane': 'n-Octano (n-C₈H₁₈)',
      'nNonane': 'n-Nonano (n-C₉H₂₀)',
      'nDecane': 'n-Decano (n-C₁₀H₂₂)',
      'Hydrogen': 'Hidrógeno (H₂)',
      'Nitrogen': 'Nitrogênio (N₂)',
      'Oxygen': 'Oxígeno (O₂)',
      'HydrogenSulfide': 'Sulfuro de Hidrógeno (H₂S)',
      'CarbonDioxide': 'Dióxido de Carbono (CO₂)',
      'WaterVapor': 'Vapor de Agua (H₂O)',
      'Helium': 'Helio',
      'Argon': 'Argón',
    },
  };
  
  String getTranslation(String key, String selectedLanguage) {

    return _translations[selectedLanguage]?[key] ?? _translations['Português']?[key] ?? key;
  }
  
  List<String> getAvailableLanguages() {

    if (_translations.isEmpty) return [];

    return _translations.keys.toList();
  }
}