class LocalizationService {
  static const Map<String, Map<String, String>> _translations = {
    'Português': {
      // --- Chaves de UI E TELAS ---
      'selecao_idioma_titulo': 'SELECIONE UM IDIOMA',
      'erro_selecao_idioma': 'Por favor, selecione um idioma antes de continuar.',
      'botao_confirmar_selecao': 'Confirmar Seleção',
      'tela_inicial': 'Menu Principal',
      'botao_iniciar': 'Começar Simulação',
      'descricao_app': 'Ferramenta para cálculo de propriedades de gás natural.',
      'titulo': 'ENTRADA DE PROPRIEDADES DO GÁS',
      'aba_densidade': 'DENSIDADE',
      'aba_massa': 'MASSA MOLECULAR',
      'aba_propriedades': 'PROPRIEDADES (Tabela)',
      'densidade_seco': 'Gás Seco',
      'densidade_umido': 'Gás Úmido',
      'label_densidade': 'Valor da Densidade ({0}) (Ex: 0.8)',
      'label_massa_molecular': 'Massa Molecular (sem unidade)',
      'dropdown_selecione': 'Selecione o Componente',
      'label_fracao': 'Fração Molar (Ex: 0.15)',
      'botao_adicionar': 'Adicionar',
      'botao_confirmar': 'CONFIRMAR',
      'cabecalho_componente': 'Componente',
      'cabecalho_fracao': 'Fração',
      'cabecalho_massa_molecular': 'Ma',
      'cabecalho_pc': 'Psc',
      'cabecalho_tc': 'Tsc',
      'total_somatoria': 'Somatória Total:',
      'erro_tabela_vazia': 'Nenhum componente informado.',
      'erro_zero': 'O valor deve ser maior que 0.',
      'erro_tabela_zero': 'A somatória das frações deve ser maior que 0.',
      'sucesso_confirmar': 'Dados confirmados com sucesso!',
      'erro_fracao_invalida': 'Por favor, insira uma fração decimal válida (> 0).',
      'erro_max_fracao_atingido': 'A soma total não pode exceder 1.0. Capacidade restante: {0}.',
      'erro_soma_maior_um': 'Erro: A soma total excedeu 1.0.',
      'componente_adicionado': 'Componente adicionado/atualizado com sucesso.',
      'componente_removido': 'Componente removido.',

      // --- Componentes de Gás ATUALIZADOS (Fórmulas em notação simples) ---
      'Methane': 'Metano (CH₄)',
      'Ethane': 'Etano (C₂H₆)',
      'Propane': 'Propano (C₃H₈)',
      'nButane': 'n-Butano (n-C₄H₁₀)',
      'iButane': 'i-Butano (i-C₄H₁₀)',
      'nPentane': 'n-Pentano (n-C₅H₁₂)',
      'iPentane': 'i-Pentano (i-C₅H₁₂)',
      'nHexane': 'n-Hexano (n-C₆H₁₄)',
      'nHeptane': 'n-Heptano (n-C₇H₁₆)',
      'nOctane': 'n-Octano (n-C₈H₁₈)',
      'nNonane': 'n-Nonano (n-C₉H₂₀)',
      'nDecane': 'n-Decano (n-C₁₀H₂₂)',
      'Hydrogen': 'Hidrogênio (H₂)',
      'Nitrogen': 'Nitrogênio (N₂)',
      'Oxygen': 'Oxigênio (O₂)',
      'HydrogenSulfide': 'Sulfeto de Hidrogênio (H₂S)',
      'CarbonDioxide': 'Dióxido de Carbono (CO₂)',
      'WaterVapor': 'Vapor d\'água (H₂O)',
      'Helium': 'Hélio',
      'Argon': 'Argônio',
    },
    'Inglês': {
      // --- Chaves de UI E TELAS ---
      'selecao_idioma_titulo': 'SELECT A LANGUAGE',
      'erro_selecao_idioma': 'Please select a language before continuing.',
      'botao_confirmar_selecao': 'Confirm Selection',
      'tela_inicial': 'Main Menu',
      'botao_iniciar': 'Start Simulation',
      'descricao_app': 'Tool for natural gas property calculation.',
      'titulo': 'GAS PROPERTIES INPUT',
      'aba_densidade': 'DENSITY',
      'aba_massa': 'MOLECULAR WEIGHT',
      'aba_propriedades': 'PROPERTIES (Table)',
      'densidade_seco': 'Dry Gas',
      'densidade_umido': 'Wet Gas',
      'label_densidade': 'Density Value ({0}) (Ex: 0.8)',
      'label_massa_molecular': 'Molecular Weight (no unit)',
      'dropdown_selecione': 'Select Component',
      'label_fracao': 'Mole Fraction (Ex: 0.15)',
      'botao_adicionar': 'Add',
      'botao_confirmar': 'CONFIRM',
      'cabecalho_componente': 'Component',
      'cabecalho_fracao': 'Fraction',
      'cabecalho_massa_molecular': 'Ma',
      'cabecalho_pc': 'Psc',
      'cabecalho_tc': 'Tsc',
      'total_somatoria': 'Total Sum:',
      'erro_zero': 'The value must be greater than 0.',
      'erro_tabela_vazia': 'No component provided.',
      'erro_tabela_zero': 'The sum of fractions must be greater than 0.',
      'sucesso_confirmar': 'Data successfully confirmed!',
      'erro_fracao_invalida': 'Please enter a valid decimal fraction (> 0).',
      'erro_max_fracao_atingido': 'Total sum cannot exceed 1.0. Remaining capacity: {0}.',
      'erro_soma_maior_um': 'Error: Total sum exceeded 1.0.',
      'componente_adicionado': 'Component successfully added/updated.',
      'componente_removido': 'Component removed.',

      // --- Componentes de Gás ATUALIZADOS (Fórmulas em notação simples) ---
      'Methane': 'Methane (CH₄)',
      'Ethane': 'Ethane (C₂H₆)',
      'Propane': 'Propane (C₃H₈)',
      'nButane': 'n-Butane (n-C₄H₁₀)',
      'iButane': 'i-Butane (i-C₄H₁₀)',
      'nPentane': 'n-Pentane (n-C₅H₁₂)',
      'iPentane': 'i-Pentane (i-C₅H₁₂)',
      'nHexane': 'n-Hexane (n-C₆H₁₄)',
      'nHeptane': 'n-Heptane (n-C₇H₁₆)',
      'nOctane': 'n-Octane (n-C₈H₁₈)',
      'nNonane': 'n-Nonane (n-C₉H₂₀)',
      'nDecane': 'n-Decane (n-C₁₀H₂₂)',
      'Hydrogen': 'Hydrogen (H₂)',
      'Nitrogen': 'Nitrogen (N₂)',
      'Oxygen': 'Oxygen (O₂)',
      'HydrogenSulfide': 'Hydrogen Sulfide (H₂S)',
      'CarbonDioxide': 'Carbon Dioxide (CO₂)',
      'WaterVapor': 'Water Vapor (H₂O)',
      'Helium': 'Helium',
      'Argon': 'Argon',
    },
    'Espanhol': {
      // --- Chaves de UI E TELAS ---
      'selecao_idioma_titulo': 'SELECCIONA UN IDIOMA',
      'erro_selecao_idioma': 'Por favor, selecciona un idioma antes de continuar.',
      'botao_confirmar_selecao': 'Confirmar Selección',
      'tela_inicial': 'Menú Principal',
      'botao_iniciar': 'Iniciar Simulación',
      'descricao_app': 'Herramienta para el cálculo de propiedades de gas natural.',
      'titulo': 'ENTRADA DE PROPIEDADES DEL GAS',
      'aba_densidade': 'DENSIDAD',
      'aba_massa': 'MASA MOLECULAR',
      'aba_propriedades': 'PROPIEDADES (Tabla)',
      'densidade_seco': 'Gas Seco',
      'densidade_umido': 'Gas Húmedo',
      'label_densidade': 'Valor de Densidad ({0}) (Ej: 0.8)',
      'label_massa_molecular': 'Masa Molecular (sin unidad)',
      'dropdown_selecione': 'Selecciona el Componente',
      'label_fracao': 'Fracción Molar (Ej: 0.15)',
      'botao_adicionar': 'Añadir',
      'botao_confirmar': 'CONFIRMAR',
      'cabecalho_componente': 'Componente',
      'cabecalho_fracao': 'Fracción',
      'cabecalho_massa_molecular': 'Ma',
      'cabecalho_pc': 'Psc',
      'cabecalho_tc': 'Tsc',
      'total_somatoria': 'Suma Total:',
      'erro_zero': 'El valor debe ser mayor que 0.',
      'erro_tabela_vazia': 'Ningún componente informado.',
      'erro_tabela_zero': 'La suma de fracciones debe ser mayor que 0.',
      'sucesso_confirmar': 'Datos confirmados con éxito!',
      'erro_fracao_invalida': 'Por favor, introduce una fracción decimal válida (> 0).',
      'erro_max_fracao_atingido': 'La suma total no puede exceder 1.0. Capacidad restante: {0}.',
      'erro_soma_maior_um': 'Error: La suma total superó 1.0.',
      'componente_adicionado': 'Componente añadido/actualizado con éxito.',
      'componente_removido': 'Componente eliminado.',

      // --- Componentes de Gás ATUALIZADOS (Fórmulas em notação simples) ---
      'Methane': 'Metano (CH₄)',
      'Ethane': 'Etano (C₂H₆)',
      'Propane': 'Propano (C₃H₈)',
      'nButane': 'n-Butano (n-C₄H₁₀)',
      'iButane': 'i-Butano (i-C₄H₁₀)',
      'nPentane': 'n-Pentano (n-C₅H₁₂)',
      'iPentane': 'i-Pentano (i-C₅H₁₂)',
      'nHexane': 'n-Hexano (n-C₆H₁₄)',
      'nHeptane': 'n-Heptano (n-C₇H₁₆)',
      'nOctane': 'n-Octano (n-C₈H₁₈)',
      'nNonane': 'n-Nonano (n-C₉H₂₀)',
      'nDecane': 'n-Decano (n-C₁₀H₂₂)',
      'Hydrogen': 'Hidrógeno (H₂)',
      'Nitrogen': 'Nitrogênio (N₂)',
      'Oxygen': 'Oxígeno (O₂)',
      'HydrogenSulfide': 'Sulfuro de Hidrógeno (H₂S)',
      'CarbonDioxide': 'Dióxido de Carbono (CO₂)',
      'WaterVapor': 'Vapor de Agua (H₂O)',
      'Helium': 'Helio',
      'Argon': 'Argón',
    },
  };
  
  String getTranslation(String key, String selectedLanguage) {
    
    return _translations[selectedLanguage]?[key] ?? _translations['Português']?[key] ?? key;
  }
  
  List<String> getAvailableLanguages() {
    
    if (_translations.isEmpty) return [];

    return _translations.keys.toList();
  }
}